### ISSUE TITLE
FR: Search for text

### ISSUE THREAD

**Issue by AvijeetPrasad** [sethyuan/logseq-plugin-smartsearch#10]
Thanks for making this great plugin. I was wondering if it can be extended to search for text also?

**Comment by sethyuan** [comment]
Currently it can filter the result list using text, this is relatively performant. I'm not sure if searching directly using text is performant enough, but it's implementable. I'll look into it when I get some spare time.

**Comment by sethyuan** [comment]
@AvijeetPrasad Case insensitive search by text is added, FYI.

**Comment by AvijeetPrasad** [comment]
It works really well. Thank you !

**Comment by sethyuan** [comment]
@AvijeetPrasad I just released a new version and the syntax for full text search is changed, you don't need to type a ";" any more and you can combine it with other conditions now. E.g, `@category, note`.
