### ISSUE TITLE
FR：support embedding block 

### ISSUE THREAD

**Issue by byheaven** [sethyuan/logseq-plugin-smartsearch#11]
Hi Seth! I use embedded block reference more frequently. It would be great that the default behavior of blocks results can be set as embedding. If it can be inserted in the "another embed" form, it will be a strong combination! Kudos!

**Comment by sethyuan** [comment]
Will work on this.

As for "Another Embed", you can turn its `globalEmbed` setting to true to have all page/block embeddings the alternative way. ;)

**Comment by sethyuan** [comment]
@byheaven 嵌入的功能已经加上了，FYI。
