### ISSUE TITLE
按快捷键没反应

### ISSUE THREAD

**Issue by bxz400** [sethyuan/logseq-plugin-smartsearch#12]
无论是默认快捷键，还是更改过几个快捷键。都没有反应……
软件和 插件都是最新版，windows11。

**Comment by sethyuan** [comment]
以下几种情况依次检查下吧：

1. 你是在文本编辑状态下触发的快捷键。
2. 检查操作系统中是否有快捷键可能会和你当前的快捷键设置有冲突。
3. 检查是否和Logseq的其它快捷键有冲突。

试试 `mod+shift+f`

**Comment by WsinGithub** [comment]
遇到了同样的问题😥

**Comment by sethyuan** [comment]
@WsinGithub 改了快捷键之后重启Logseq试试。
