### ISSUE TITLE
[FR] some feature requests

### ISSUE THREAD

**Issue by cannibalox** [sethyuan/logseq-plugin-smartsearch#13]
Your plugin is awesome, this should be the default search in logseq !

Some ideas :
- let the user customize more options, for instance  :
  -  custom triggers (I believe a lot of people use `@` for contacts, I would prefer to use `::` for properties, as it is more inline with the default syntax of logseq, so instead of `@property`, I want to use `::property`)
  - re-assign shortcuts/modifiers (eg: if I want to use `shift` to open in sidebar and `enter` to open file)
- an option to invoke smartsearch when **not** in edit mode : in this case, maybe it could look-like/replace the native search bar ? 

feel free to disregard the request. Anyway, thanks for your great plugins !

**Comment by cannibalox** [comment]
> There is a search provider feature in Logseq and I have integrated it in the plugin

I saw that option but I don't understand what it does, is there any doc or link about the search provider ?

>BTW, I'm not sure it's a good idea to allow users to customize the search syntax, it could introduce syntax conflicts with future implementations. The same is with the modifiers.
yes, I guess it would over-complicate things... some of the modifiers seem a bit inconsistent with the default behavior of logseq, but it's not a big deal, the benefits from the plugin massively outweight these minor nitpicks. 
thanks again.

**Comment by sethyuan** [comment]
When you enable the search provider setting, Logseq's search will become like this:

![image](https://user-images.githubusercontent.com/3410293/226074136-c6187f6c-c163-494a-bce1-862e27960039.png)

The interface is usable, but it lacks features like autocompletion.

**Comment by cannibalox** [comment]
wow this is exactly what I need ! you should add a small explanation for the search provider to the documentation/readme, I didn't realize you could already use smartsearch within the native search bar, awesome !
Thanks again !

**Comment by sethyuan** [comment]
I updated a new version that supports triggering in non-editing mode. Smart Search offers more completion features than Logseq's builtin search provider, so I'd recommend you to give this global mode a try.
