### ISSUE TITLE
`@property >value` breaking when using `:property/separated-by-commas #{}`

### ISSUE THREAD

**Issue by cannibalox** [sethyuan/logseq-plugin-smartsearch#14]
if a property value is set to autolink in config.edn with `:property/separated-by-commas #{}`,
then searching for `@property >value` will not work (or any calculation operator <,>,>=,<=, =)

to repro:
1. create file a with property::number like
```
year:: 2020
```
2. in config.edn, set `:property/separated-by-commas #{:year}` , reindex
3. search with smartsearch `@year >2000` 

This is probably a logseq issue though ? not sure if you can do something or if this should open an issue on logseq ?

**Comment by sethyuan** [comment]
This because 2020 is being converted into a page reference rather than a number when you turn the autolink on.
