### ISSUE TITLE
FEATURE REQUEST Remember previous smart searches

### ISSUE THREAD

**Issue by adxsoft** [sethyuan/logseq-plugin-smartsearch#15]
First let me say this is an amazing plugin that is sorely needed in the core of Logseq. It adds the power to searching without the need for resorting to queries. 

I've turned on the _search provider feature_ in the plugin settings to add the smart search tab to the default Logseq search UI.

I've noticed that only recent DEFAULT searches are listed but no SMART SEARCHES. 

It would be great if the SMART searched could appear in the recent search list

Thank you for your plugin!

**Comment by sethyuan** [comment]
I just checked, it seems that the search history is shared between the default one and the Smart Search one, just click on an history entry and switch to the Smart Search tab.

**Comment by adxsoft** [comment]
Brilliant. Thanks!
