### ISSUE TITLE
Very minor UI bug on Mac leaving ~~~~ in block

### ISSUE THREAD

**Issue by adxsoft** [sethyuan/logseq-plugin-smartsearch#17]
Not sure if this applies only to Mac but whenever I do a smart search in a block using the shortcut key (default is ctrl space but in my case I reset it to Cmd Shift S) ..  if I press the Esc key to exit smart search, it leaves  ~~~~ in the block and you have to manually delete the four characters ~~~~

**Comment by sethyuan** [comment]
I think it is the shortcut you assigned that is causing ~~~~
Can you try assigning a different shortcut?

**Comment by sethyuan** [comment]
Confirmed the shortcut conflict is the cause.
