### ISSUE TITLE
[Bug] It is strange that cannot search some texts.

### ISSUE THREAD

**Issue by mzwlevi** [sethyuan/logseq-plugin-smartsearch#22]
Such as `logseq` or `task`
But others can be searched: Love
<img width="1066" alt="Screenshot 2023-12-09 at 11 52 29" src="https://github.com/sethyuan/logseq-plugin-smartsearch/assets/78029539/ce14be94-54d5-41e0-9129-a6601cd6f464">
<img width="1066" alt="Screenshot 2023-12-09 at 11 52 18" src="https://github.com/sethyuan/logseq-plugin-smartsearch/assets/78029539/034907f4-7c3b-4331-8d95-19f07695d012">
<img width="1066" alt="Screenshot 2023-12-09 at 11 51 12" src="https://github.com/sethyuan/logseq-plugin-smartsearch/assets/78029539/8ed5da9e-b8bc-4457-87c3-2d79d93d5904">

**Comment by sethyuan** [comment]
A re-index may solve the problem.

**Comment by mzwlevi** [comment]
> A re-index may solve the problem.

Solved it, your plugins are awesome, thank you for your work : )
