### ISSUE TITLE
Using `##` to include childs leads to degraded performance and in instances of large graphs, results do not return

### ISSUE THREAD

**Issue by nmartin84** [sethyuan/logseq-plugin-smartsearch#6]
Hi there! Great plugin and I really love it. I noticed that when you use double `##` to search for child blocks under a page-reference, it returns everything, no matter how deep, and in situations where you have a very large graph this can end up returning 1000's of blocks, which leads to some poor performance. In my instance the plugin fails to return any results because there's just simply too many results. 

Could this be configured to only return the parent block underneath the query? I'll give an example below.

How it works today:
<img width="743" alt="Screenshot 2022-11-17 103544" src="https://user-images.githubusercontent.com/38045018/202504548-510cafb3-7a2a-488f-a052-d02f39ba4082.png">

How I would like it to work:
<img width="610" alt="Screenshot 2022-11-17 103802" src="https://user-images.githubusercontent.com/38045018/202504635-a2b573da-9096-45af-a297-10f3fc1f69bf.png">

**Comment by nmartin84** [comment]
Either that or maybe improve the way the current query works? So that if I entered `##projects; logseq`.. Before it returns the initial results for `##projects`, it goes straight to querying `##projects; logseq` instead?

**Comment by sethyuan** [comment]
Hi @nmartin84 , I agree on just returning the immediate children of `##tag`, returning all descendants is too power consuming. Is this working for you @pstuifzand ?

Regarding the `;` filter, it is a fuzzy search, and it's not yet possible to pass custom functions to DB query (although I think it won't help with performance passing it to the DB query anyway).

**Comment by sethyuan** [comment]
I changed the implementation and released a new version. Now `##` returns only itself and its immediate children, not all descendants.

**Comment by pstuifzand** [comment]
I think that if you have enough direct childs, you will still run into the same problem. I guess this only happens less.

Another solution would be to limit the results from the query and showing less blocks, perhaps only rerunning the query when the filter changes. I'm don't know if this is possible with the datascriptQuery function. 
You would need limit/offset (or similar) functionality in the database. @sethyuan Do you know if that exists?

**Comment by sethyuan** [comment]
> I'm don't know if this is possible with the datascriptQuery function.
> You would need limit/offset (or similar) functionality in the database. @sethyuan Do you know if that exists?

Not that I know of.

Still, I think we can do both. On one hand, **limiting `##` results to only immediate children** do help with reducing the amount of results to display (bringing out all descendants is not that necessary); on the other hand, I can try **add a limit on how much results to display, say the first 100**. This reduces the number of DOM elements rendered which can improve performance.

BTW, virtual list technologies do not apply here because results have variable height depending on content and the handling of arrow movements (from the first to the last and vice versa) requires DOM elements to be pre-rendered.

**Comment by sethyuan** [comment]
The 2 points mentioned above are now implemented (and released).

I also reused the previous result if only the `;` filter part is changed.

**Comment by nmartin84** [comment]
@sethyuan  Tested - appears to be working well. Fuzzy searches will need some improvement when possible, as is it returns a lot of false positives. Is it possible to use the clojure function `clojure.string/includes?` and treat white spaces as AND operators?

Overall though `##` is looking much better now! This will be a very useful tool.

**Comment by sethyuan** [comment]
Great, then I'm closing this ticket.

Also, the fuzzy search works by matching sub-strings in order, e.g, with a phrase like "hello world", I can match it by writing `hellow`, or `hwor`, or `hllow`, or `h w`, etc. This offers maximum flexibility on how one can search for what he/she wants. If you're getting too many matches, you can always try to be more specific by typing more characters.

**Comment by sethyuan** [comment]
@pstuifzand @nmartin84 , Recently I came across a case that made me think about `##` behavior again. Let's say I want to search for `##project a, #feature`, that is, all features under project a, no matter how deep. With the current behavior, it would only return those immediate children that has a #feature, which is not what I want. So, I'm thinking on changing `##` to return all descendants again.

**Comment by pstuifzand** [comment]
Perhaps it's an option to use a different syntax for direct descendants?

Taking inspiration from CSS where it would be  .tag > .child

I could work like this `#>child`

The `>` instead of the second `#` would make it direct instead of all.

**Comment by sethyuan** [comment]
I just released a new version with `##` returning all descendants. It's meant to be used in combination with other conditions. Can you help test its performance? I don't think it's needed to introduce a new syntax if performance is acceptable.

**Comment by nmartin84** [comment]
@sethyuan - Performance wise it's still a bit of a problem for one of my graphs where i've got 1000s of blocks being returned, it's doable for now though. I would still like for the two to be different. As it is this feature is kind of pointless when I am trying to search through my project blocks, since it's returning so many that I now have to filter through with the right selection of keywords. It's faster to just pull the project page and look at the listing of projects from there. In my use case I have a lot of projects that have very similar keywords to one another, so filtering through a selection of keywords still ends up returning quite a few results which makes it very difficult to find the one I am looking for.

**Comment by nmartin84** [comment]
@sethyuan sounds great! Thanks!
