### ISSUE TITLE
Add small hint below input

### ISSUE THREAD

**Issue by pstuifzand** [sethyuan/logseq-plugin-smartsearch#7]
I was looking at a way to make it clear how to the input works and show what it can do. I came up with the following. A similar tag could be done for the different types of search syntax. Is this something you are interested in?

![image](https://user-images.githubusercontent.com/64524/203634472-cebe30aa-507c-489e-b495-611f45cc4546.png)

**Comment by sethyuan** [comment]
Good idea, providing hints to users may improve UX. I'll think about it too.

**Comment by sethyuan** [comment]
I moved the hint up to make it adapt the 2 input states, what do you think? I also added a placeholder giving a typical usage example.

![image](https://user-images.githubusercontent.com/3410293/203699279-7e1d400b-0938-48dd-bc7b-9a6b16e991b5.png)

![image](https://user-images.githubusercontent.com/3410293/203699528-0a642365-dd47-4310-a8ae-23a65bf20100.png)

**Comment by pstuifzand** [comment]
Yeah, I think this would help a lot. Placeholder is also useful. 

Having it below would make it less important compared to input. But perhaps it interferes with dropdown.

**Comment by sethyuan** [comment]
OK, new version is released.
