### ISSUE TITLE
using the default shortcut key ctrl+space can't to call the input out

### ISSUE THREAD

**Issue by fbl1999** [sethyuan/logseq-plugin-smartsearch#8]
编辑状态下使用ctrl+space快捷键没有任何反应, 是还需要其他设置吗?

**Comment by sethyuan** [comment]
有可能是你有一样的系统快捷键，冲突了，可以换个试试。

**Comment by fbl1999** [comment]
谢谢你做出这么好用的插件👍, 可能是版本的问题,我刚刚重新下载安装0.8.12就可以使用了.

**Comment by sethyuan** [comment]
OK

**Comment by TookiTheGreat** [comment]
I am using Logseq 0.8.15 and the latest version of your plugin. Whatever key combination I put in the settings, I can't get the input window to pop up.
