### ISSUE TITLE
Smart Search doesn't give me an input window

### ISSUE THREAD

**Issue by TookiTheGreat** [sethyuan/logseq-plugin-smartsearch#9]
I am using Logseq 0.8.15 and the latest version of your plugin. Whatever key combination I put in the settings, I can't get the input window to pop up.

_Originally posted by @TookiTheGreat in https://github.com/sethyuan/logseq-plugin-smartsearch/issues/8#issuecomment-1373478328_

**Comment by sethyuan** [comment]
You must restart Logseq after changing the shortcut key setting.

**Comment by TookiTheGreat** [comment]
Ah, that seems to work. Thanks for the quick reply.
